services:
  - type: web
    name: stonedigger-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: Stonedigger_bot
      - key: PUBLIC_BASE_URL
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STARS_PRICE
        value: "100"
